version: '3'

services:
   mysql:
     platform: linux/x86_64
     image: mysql:5.7
     container_name: go-mysql
     ports:
       - 3306:3306
     restart: always
     environment:
       MYSQL_PASSWORD: password
       MYSQL_USER: user
       MYSQL_DB: go-mysql-api
       MYSQL_ROOT_PASSWORD: password
       DATABASE_HOST: localhost